import type { ListingType } from "../types/marketplace";

export const initialListingTypes: ListingType[] = [
  {
    id: "youtube",
    key: "youtube",
    name: "YouTube",
    enabled: true,
    freeListingAllowance: 1,
    listingFeeMinor: 100,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 1,
  },
  {
    id: "facebook",
    key: "facebook",
    name: "Facebook",
    enabled: true,
    freeListingAllowance: 1,
    listingFeeMinor: 100,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 2,
  },
  {
    id: "instagram",
    key: "instagram",
    name: "Instagram",
    enabled: true,
    freeListingAllowance: 1,
    listingFeeMinor: 100,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 3,
  },
  {
  id: "x",
  key: "x",
  name: "X",
  enabled: true,

  freeListingAllowance: 1,
  listingFeeMinor: 100,
  minimumBoostMinor: 100,

  boostingEnabled: true,
  sortOrder: 4,
},
  {
    id: "app",
    key: "app",
    name: "App",
    enabled: true,
    freeListingAllowance: 0,
    listingFeeMinor: 299,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 4,
  },
  {
    id: "startup",
    key: "startup",
    name: "Startup",
    enabled: true,
    freeListingAllowance: 0,
    listingFeeMinor: 499,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 5,
  },
  {
    id: "website",
    key: "website",
    name: "Website",
    enabled: true,
    freeListingAllowance: 1,
    listingFeeMinor: 199,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 6,
  },
  {
    id: "other",
    key: "other",
    name: "Other",
    enabled: true,
    freeListingAllowance: 1,
    listingFeeMinor: 199,
    minimumBoostMinor: 100,
    boostingEnabled: true,
    sortOrder: 99,
  },
];